# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  scrollHeight: 10 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
  sidePanelWidth: 0.22 # number from 0 to 1
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - "#D14242"
      - bold
    inactiveBorderColor:
      - "#323232"
    optionsTextColor:
      - "#ffffff"
    selectedLineBgColor:
      - "#323232"
    cherryPickedCommitBgColor:
      - "#323232"
    cherryPickedCommitFgColor:
      - "#A7A7A7"
    unstagedChangesColor:
      - "#DF6464"
    defaultFgColor:
      - "#A7A7A7"
    searchingActiveBorderColor:
      - "#A7A7A7"
  commitLength:
    show: true
  branchColors:
    "release": "#eed49f"
    "hotfix": "#ed8796"
    "feature": "#a6da95"
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  showNumstatInFilesView: true
  commandLogSize: 5
  showDivergenceFromBaseBranch: "arrowAndNumber"
  filterMode: "fuzzy"
  showPanelJumps: false
  skipRewordInEditorWarning: true # for skipping the confirmation before launching the reword editor
  border: "rounded" # one of 'single' | 'double' | 'rounded' | 'hidden'
  statusPanelView: allBranchesLog
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --dark --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' {{branchName}} --"
  parseEmoji: true
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit  --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'
os:
  editPreset: "nvim-remote"
  # edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}})'
disableStartupPopups: true
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip' | 'quit'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>" # alternative/alias of quit
    return: "<esc>" # return to previous menu, will quit if there's nowhere to return
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>" # goto the next panel
    prevItem: "<up>" # go one line up
    nextItem: "<down>" # go one line down
    prevItem-alt: "k" # go one line up
    nextItem-alt: "j" # go one line down
    prevPage: "K" # go to next page in list
    nextPage: "J" # go to previous page in list
    gotoTop: "<" # go to top of list
    gotoBottom: ">" # go to bottom of list
    scrollLeft: "H" # scroll left within list view
    scrollRight: "L" # scroll right within list view
    prevBlock: "<left>" # goto the previous block / panel
    nextBlock: "<right>" # goto the next block / panel
    prevBlock-alt: "" # goto the previous block / panel
    nextBlock-alt: "" # goto the next block / panel
    jumpToBlock: ["1", "2", "3", "4", "5"] # goto the Nth block / panel
    nextMatch: "n"
    prevMatch: "N"
    optionMenu: <disabled> # show help menu
    optionMenu-alt1: "?" # show help menu
    select: "<space>"
    goInto: "<enter>"
    openRecentRepos: "<c-r>"
    confirm: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>" # main panel scroll up
    scrollDownMain: "<pgdown>" # main panel scroll down
    scrollUpMain-alt1: "<c-u>" # main panel scroll up
    scrollDownMain-alt1: "<c-d>" # main panel scroll down
    scrollUpMain-alt2: "<disabled>" # main panel scroll up
    scrollDownMain-alt2: "<disabled>" # main panel scroll down
    executeShellCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "l"
    prevTab: "h"
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: "<c-s>"
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>" # deprecated
    copyToClipboard: "<c-o>"
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseContextInDiffView: "}"
