[font]
size = 8.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Default Colors
[colors.primary]
background = '#121212'
foreground = '#f5f5f5'

# Selection Colors
[colors.cursor]
cursor = '#C53030'
text = '#121212'

# Normal Colors
[colors.normal]
black = '#121212'
red = '#B14242'
green = '#B14242'
yellow = '#E49A44'
blue = '#DF6464'
magenta = '#323232'
cyan = '#B14242'
white = '#737373'

# Bright Colors
[colors.bright]
black = '#949494'
red = '#B14242'
green = '#D87C4A'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'


